#! /bin/bash

VERSION="1.0.2"
DATE="12/08/2022"

echo "eolicas-newave-dados"
echo "Gerência de Metodologias e Modelos Energéticos - PEM / ONS"
echo "Versão ${VERSION} - ${DATE}"

USERINSTALLDIR=/usr/lib
INSTALLDIR=${USERINSTALLDIR}/eolicas-newave/dados

# Checks if application is installed
if [ ! -d $INSTALLDIR ]; then
    echo "Aplicação não encontrada..."
    exit 1
fi

RUN=$INSTALLDIR/main/execucao_completa.r
export INSTALLDIR=$INSTALLDIR

echo "Executando"
echo "------------------"

echo Rscript $RUN $*
Rscript $RUN $*
